### ISSUE TITLE
Creates empty exports

### ISSUE THREAD

**Issue by wmertens** [homer0/cjs2esm#10]
Happens when rewriting a file that is already es module (but transpiled via webpack):

```
export default {foo: true}
```

becomes

```
const exported = {foo: true}

export default exported
export const {} = exported
export const {foo} = exported
```

**Comment by homer0** [comment]
@wmertens Hey 👋 , can you provide me with the code generated by webpack? I want to check, but my theory is that your webpack is using Babel, and the output is incompatible with the `named-export-generation` transformation.
